/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as PacksNewIndexRouteImport } from './routes/packs/new/index'
import { Route as PacksPackSlugIndexRouteImport } from './routes/packs/$packSlug/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PacksPackSlugEditIndexRouteImport } from './routes/packs/$packSlug/edit/index'
import { Route as PacksPackSlugTopicsNewRouteImport } from './routes/packs/$packSlug/topics/new'
import { Route as PacksPackSlugTopicsTopicSlugIndexRouteImport } from './routes/packs/$packSlug/topics/$topicSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksNewIndexRoute = PacksNewIndexRouteImport.update({
  id: '/packs/new/',
  path: '/packs/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackSlugIndexRoute = PacksPackSlugIndexRouteImport.update({
  id: '/packs/$packSlug/',
  path: '/packs/$packSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackSlugEditIndexRoute = PacksPackSlugEditIndexRouteImport.update({
  id: '/packs/$packSlug/edit/',
  path: '/packs/$packSlug/edit/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackSlugTopicsNewRoute = PacksPackSlugTopicsNewRouteImport.update({
  id: '/packs/$packSlug/topics/new',
  path: '/packs/$packSlug/topics/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackSlugTopicsTopicSlugIndexRoute =
  PacksPackSlugTopicsTopicSlugIndexRouteImport.update({
    id: '/packs/$packSlug/topics/$topicSlug/',
    path: '/packs/$packSlug/topics/$topicSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/u/$username': typeof UUsernameRoute
  '/auth/': typeof AuthIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/play/': typeof PlayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/packs/$packSlug/': typeof PacksPackSlugIndexRoute
  '/packs/new/': typeof PacksNewIndexRoute
  '/packs/$packSlug/topics/new': typeof PacksPackSlugTopicsNewRoute
  '/packs/$packSlug/edit/': typeof PacksPackSlugEditIndexRoute
  '/packs/$packSlug/topics/$topicSlug/': typeof PacksPackSlugTopicsTopicSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/u/$username': typeof UUsernameRoute
  '/auth': typeof AuthIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/packs': typeof PacksIndexRoute
  '/play': typeof PlayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/packs/$packSlug': typeof PacksPackSlugIndexRoute
  '/packs/new': typeof PacksNewIndexRoute
  '/packs/$packSlug/topics/new': typeof PacksPackSlugTopicsNewRoute
  '/packs/$packSlug/edit': typeof PacksPackSlugEditIndexRoute
  '/packs/$packSlug/topics/$topicSlug': typeof PacksPackSlugTopicsTopicSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/u/$username': typeof UUsernameRoute
  '/auth/': typeof AuthIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/packs/': typeof PacksIndexRoute
  '/play/': typeof PlayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/packs/$packSlug/': typeof PacksPackSlugIndexRoute
  '/packs/new/': typeof PacksNewIndexRoute
  '/packs/$packSlug/topics/new': typeof PacksPackSlugTopicsNewRoute
  '/packs/$packSlug/edit/': typeof PacksPackSlugEditIndexRoute
  '/packs/$packSlug/topics/$topicSlug/': typeof PacksPackSlugTopicsTopicSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/u/$username'
    | '/auth/'
    | '/leaderboard/'
    | '/packs/'
    | '/play/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/packs/$packSlug/'
    | '/packs/new/'
    | '/packs/$packSlug/topics/new'
    | '/packs/$packSlug/edit/'
    | '/packs/$packSlug/topics/$topicSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/u/$username'
    | '/auth'
    | '/leaderboard'
    | '/packs'
    | '/play'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/packs/$packSlug'
    | '/packs/new'
    | '/packs/$packSlug/topics/new'
    | '/packs/$packSlug/edit'
    | '/packs/$packSlug/topics/$topicSlug'
  id:
    | '__root__'
    | '/'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/u/$username'
    | '/auth/'
    | '/leaderboard/'
    | '/packs/'
    | '/play/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/packs/$packSlug/'
    | '/packs/new/'
    | '/packs/$packSlug/topics/new'
    | '/packs/$packSlug/edit/'
    | '/packs/$packSlug/topics/$topicSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  UUsernameRoute: typeof UUsernameRoute
  AuthIndexRoute: typeof AuthIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  PacksIndexRoute: typeof PacksIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  PacksPackSlugIndexRoute: typeof PacksPackSlugIndexRoute
  PacksNewIndexRoute: typeof PacksNewIndexRoute
  PacksPackSlugTopicsNewRoute: typeof PacksPackSlugTopicsNewRoute
  PacksPackSlugEditIndexRoute: typeof PacksPackSlugEditIndexRoute
  PacksPackSlugTopicsTopicSlugIndexRoute: typeof PacksPackSlugTopicsTopicSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs/'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/new/': {
      id: '/packs/new/'
      path: '/packs/new'
      fullPath: '/packs/new/'
      preLoaderRoute: typeof PacksNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packSlug/': {
      id: '/packs/$packSlug/'
      path: '/packs/$packSlug'
      fullPath: '/packs/$packSlug/'
      preLoaderRoute: typeof PacksPackSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packSlug/edit/': {
      id: '/packs/$packSlug/edit/'
      path: '/packs/$packSlug/edit'
      fullPath: '/packs/$packSlug/edit/'
      preLoaderRoute: typeof PacksPackSlugEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packSlug/topics/new': {
      id: '/packs/$packSlug/topics/new'
      path: '/packs/$packSlug/topics/new'
      fullPath: '/packs/$packSlug/topics/new'
      preLoaderRoute: typeof PacksPackSlugTopicsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packSlug/topics/$topicSlug/': {
      id: '/packs/$packSlug/topics/$topicSlug/'
      path: '/packs/$packSlug/topics/$topicSlug'
      fullPath: '/packs/$packSlug/topics/$topicSlug/'
      preLoaderRoute: typeof PacksPackSlugTopicsTopicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  UUsernameRoute: UUsernameRoute,
  AuthIndexRoute: AuthIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  PacksIndexRoute: PacksIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  PacksPackSlugIndexRoute: PacksPackSlugIndexRoute,
  PacksNewIndexRoute: PacksNewIndexRoute,
  PacksPackSlugTopicsNewRoute: PacksPackSlugTopicsNewRoute,
  PacksPackSlugEditIndexRoute: PacksPackSlugEditIndexRoute,
  PacksPackSlugTopicsTopicSlugIndexRoute:
    PacksPackSlugTopicsTopicSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
